CBA Settings changes
Project-Hatchet/public_h-60 pull request #127
Opened 2021-03-31 02:51 UTC by BroBeansCPG

**When merged this pull request will:**
- Clear confusion on H60 settings
- Relocate H60 settings to relevant modules
- Rename settings/vars to "disabled" instead of "enabled"
- Create 'Debug' Sub-category under UH-60M Settings to keep it neat

2021-09-04 09:46 UTC, BroBeansCPG commented
This will have to wait until framework update

2021-09-08 20:41 UTC, A26mike commented
Rgr

2021-09-09 03:28 UTC, A26mike commented
What is the current status of this ? does it need to be merged or closed

2021-09-09 10:29 UTC, BroBeansCPG commented
See above. 

Linked to framework update

2021-09-09 14:07 UTC, A26mike commented
What do we need framework wise ?

2021-09-09 21:43 UTC, BroBeansCPG commented
It’s a pretty substantial update, 

Was talking to brett about it, unsure if he has time but we need an experienced programmer to finish the update

2021-11-11 22:42 UTC, YannikH requested changes
Target branch should be changed to main

2023-11-04 09:40 UTC, closed without merging