ACE interactions for adding door tape numbers & closeable doors
Project-Hatchet/public_h-60 pull request #129
Opened 2021-04-04 03:54 UTC by sevn10

**When merged this pull request will:**
- Add ability via ACE interaction on the outside of the helo to choose or clear the use of door tape numbers
- Add ability via ACE interaction on the outside of the helo to close and open cabin doors

2021-04-14 00:11 UTC, BroBeansCPG commented
Do checks need to be added to determine whether or not something is blocking the doors? 

Consider https://github.com/Project-Hatchet/public_h-60/blob/9fd7416d1b8d54a6ad8bfc9caf0f5f73407fbeeb/addons/uh60_misc/functions/fnc_canInteractCabinDoor.sqf

2021-09-04 09:44 UTC, BroBeansCPG commented
Maybe explore the using of ace interaction on the door handle memory point

2021-09-04 17:20 UTC, sevn10 commented
That could be good, but I believe I'll need to be reminded on how to find that memory point. I can ping you on discord to clarify.

2021-09-09 03:31 UTC, A26mike commented
What is the current status of this.  @sevn10 ?

@AdozenBABYdogs give this a test and let me know the results

2021-09-09 04:53 UTC, sevn10 commented
@A26mike I need to talk to you or brobeans, I'm not sure how to find the ACE memory point. I could try to revise this afterwards.

2021-09-09 10:30 UTC, BroBeansCPG commented
> What is the current status of this. @sevn10 ?
> 
> @AdozenBABYdogs give this a test and let me know the results

Also the door numbers were added in #130

2021-09-09 10:30 UTC, BroBeansCPG commented
> @A26mike I need to talk to you or brobeans, I'm not sure how to find the ACE memory point. I could try to revise this afterwards.

DM me on discord

2021-09-16 16:12 UTC, AdozenBABYdogs commented
> **When merged this pull request will:**
> 
> * Add ability via ACE interaction on the outside of the helo to choose or clear the use of door tape numbers
> * Add ability via ACE interaction on the outside of the helo to close and open cabin doors

Door numbers work, doors open from the outside

2021-09-16 16:18 UTC, AdozenBABYdogs commented
Suggested next step

- add animation for exiting with doors closed
- add check for if doors are open, if they are not, animate the player getting out

2021-10-12 08:12 UTC, YannikH commented
@sevn10 The mempoint names for the door handles are cabindoor_L_handle and cabindoor_R_handle

2021-11-30 15:54 UTC, ampersand38 commented
Please see vtx_uh60_misc_fnc_canInteractCabinDoor for [un]locking the door seats on MH and HH models.

How often do you need to change door numbers mid-mission? It's probably be better left to mission-maker setup, I'm thinking. Maybe separate PRs for doors and numbers.

2021-11-30 15:55 UTC, ampersand38 requested changes

2021-11-30 15:55 UTC, ampersand38 commented on addons/uh60_misc/XEH_postInit.sqf
> +_condition = {((_this select 0) animationPhase "cabindoor_l") == 0};
Needs to [un]lock door seats. See vtx_uh60_misc_fnc_canInteractCabinDoor

2024-09-30 17:12 UTC, Riverman02 commented
These features have been added, can't this be closed?

2024-10-01 00:42 UTC, closed without merging