Adds HMD Brightness controls to the FMS
Project-Hatchet/public_h-60 pull request #217
Opened 2021-12-07 01:44 UTC by FatLurch

**When merged this pull request will:**
- Adds "BRT" and "DIM" controls to HMD FMS screen
- BRT and DIM adjust HMD brightness
- Default HMD color set to `[0,1,0]`
- Partially address #192

2021-12-14 22:56 UTC, YannikH requested changes
Thsi will conflict with #221 as that takes dummy1 and makes it dummy11, coordinate with ampersand to make sure that this'll work after merged, I will approve it after

2021-12-15 07:05 UTC, FatLurch commented
> Thsi will conflict with #221 as that takes dummy1 and makes it dummy11, coordinate with ampersand to make sure that this'll work after merged, I will approve it after

I worked with ampersand - sounded like pylon indices up to dummy 7 were real and in use, the rest were provisional. I trimmed back to the ones that were in use and used 8 and 9 for the two HMD different HMD brightnesses

2021-12-18 15:22 UTC, YannikH approved these changes
Looks good

2021-12-18 23:55 UTC, ampersand38 approved these changes

2021-12-18 23:55 UTC, ampersand38 commented on addons/uh60_anvishud/config/MFD/HMD.hpp
> +color[] = {0,1,0,pylonAmmoRelative11};
Why is the color changed? What does it look like now?

2021-12-18 23:55 UTC, ampersand38 commented on addons/uh60_anvishud/XEH_PREP.hpp
> +PREP(Hud_Brt);
camelCase preferred.
hudDim
hudBrt

2021-12-18 23:55 UTC, ampersand38 commented on addons/uh60_fms/config/interaction.hpp
> +    buttonUp = "[] call vtx_uh60_anvishud_fnc_Hud_Dim;";
`buttonUp` code gets `_vehicle` passed through it. If you use `call fnc` then you already have it as a param.
see https://github.com/Project-Hatchet/H-60/blob/Main/addons/uh60_doorguns/config/cfgVehicles.hpp#L30
and https://github.com/Project-Hatchet/H-60/blob/Main/addons/uh60_doorguns/functions/fnc_coverSwitch.sqf

The 2 functions do the same thing, could consolidate to 
`[_vehicle, _delta] call vtx_uh60_anvishud_fnc_adjustBrightness` or similar, but not a big deal right now since we have to deal with colors.

2021-12-18 23:55 UTC, ampersand38 commented on addons/uh60_anvishud/functions/fnc_setup.sqf
> +vehicle player setAmmoOnPylon [11, 600];	//Configure the default HUD brightness
Should be a CBA setting, although could wait for integrated setting via RGBA color.

2021-12-18 23:55 UTC, ampersand38 commented on addons/uh60_anvishud/functions/fnc_Hud_Brt.sqf
> + 	vehicle player setAmmoOnPylon [11, _ammoCount + 100];
if it's somehow 999 then it'll end up with 1099. Better off with something like 
`0 max _val min 1000`

2021-12-21 15:26 UTC, ampersand38 commented
https://www.youtube.com/watch?v=YacpD5zkACI

2021-12-21 16:36 UTC, FatLurch commented
https://youtu.be/YacpD5zkACI

2022-01-05 15:22 UTC, closed without merging