Bugfix/startup order
Project-Hatchet/public_h-60 pull request #417
Opened 2023-07-13 15:45 UTC by AdozenBABYdogs

**When merged this pull request will:**
- This merge prevents the starter from activating if the PCLs are not in the "OFF" position

2023-07-17 03:00 UTC, BroBeansCPG approved these changes
lgtm

2023-07-17 03:10 UTC, BroBeansCPG commented
fixes #416

2023-11-03 19:19 UTC, YannikH requested changes

2023-11-03 19:19 UTC, YannikH commented on addons/uh60_sfmplus/functions/fn_standbyInst.sqf
> +		_vehicle setVariable ["vtx_uh60_acft_stbyInstBatt", _stbyInstBatt];
this is currently local to your machine, this should be shared over the network

2023-11-03 19:19 UTC, YannikH commented on addons/uh60_sfmplus/functions/fn_standbyInst.sqf
> +		_vehicle setVariable ["vtx_uh60_acft_stbyInstBatt", _stbyInstBatt];
this is currently local to your machine, this should be shared over the network

2023-11-03 19:59 UTC, YannikH approved these changes
LGTM

2023-11-03 20:07 UTC, merged